version: '3'
services:
    nginx:
        image: nginx:1.13
        container_name: "mriqs-nginx"
        environment:
            - APP_DIR
        ports:
            - 80:80
        links:
            - "php-fpm:php.host"
        volumes:
            - "${APP_DIR}:/mriqs:rw"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php-fpm
            - mysql
        # logging:
        #     driver: "syslog"
        #     options:
        #         syslog-facility: "local0"
        #         tag: "mriqs-nginx"

    php-fpm:
        build: ./docker/php
        container_name: "mriqs-php"
        links:
            - "mysql:mysql.host"
        entrypoint: /bin/bash /tmp/entrypoint.sh
        working_dir: /mriqs
        volumes:
            - "${APP_DIR}:/mriqs:rw"
            - "./docker/php/entrypoint.sh:/tmp/entrypoint.sh"
        # logging:
        #     driver: "syslog"
        #     options:
        #         syslog-facility: "local0"
        #         tag: "mriqs-php"

    mysql:
        image: mysql:5.6
        container_name: "mriqs-mysql"
        environment:
            - MYSQL_DATA_DIR
            - MYSQL_ROOT_PASSWORD
        ports:
            - 127.0.0.1:3306:3306
        volumes:
            - "${MYSQL_DATA_DIR}:/var/lib/mysql"
            - "${MYSQL_BCKP_DIR}:/var/backup"
        # logging:
        #     driver: "syslog"
        #     options:
        #         syslog-facility: "local0"
        #         tag: "mriqs-mysql"